server {
  listen 8000;
  server_name _;

  location = /health {
    access_log off;
    default_type application/json;
    return 200 '{"status":"ok"}';
  }

  location /auth/v1/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://auth:9999/;
  }

  location /rest/v1/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://rest:3000/;
  }
}
