create or replace function public.fn_streak(uid uuid default auth.uid()) returns integer language sql stable security invoker set search_path=pg_catalog,public as $$
with recursive anchor as (select case when exists(select 1 from public.check_ins where user_id=uid and check_date=(timezone('America/Sao_Paulo',now()))::date) then (timezone('America/Sao_Paulo',now()))::date when exists(select 1 from public.check_ins where user_id=uid and check_date=(timezone('America/Sao_Paulo',now()))::date-1) then (timezone('America/Sao_Paulo',now()))::date-1 end d), walk(day) as (select d from anchor where d is not null union all select w.day-1 from walk w where exists(select 1 from public.check_ins where user_id=uid and check_date=w.day-1)) select count(*)::int from walk;
$$;
create or replace view public.v_user_points with(security_invoker=true) as select p.id user_id,coalesce(sum(e.points),0)::bigint total,coalesce(sum(e.points) filter(where e.event_date>=date_trunc('week',(timezone('America/Sao_Paulo',now()))::date)::date),0)::bigint weekly from public.profiles p left join public.points_events e on e.user_id=p.id group by p.id;

create or replace function public.rpc_check_in(input_minutes integer default 0) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare uid uuid:=auth.uid(); cid bigint; d date:=(timezone('America/Sao_Paulo',now()))::date; s integer; awarded integer:=10;
begin
 if uid is null then raise exception using errcode='28000',message='Sessão inválida'; end if;
 if input_minutes is null or input_minutes<0 or input_minutes>1440 then raise exception using errcode='22023',message='Minutos inválidos'; end if;
 insert into public.check_ins(user_id,check_date,minutes) values(uid,d,input_minutes) returning id into cid;
 insert into public.points_events(user_id,source,ref_id,points,event_date) values(uid,'check_in',cid,10,d);
 s:=public.fn_streak(uid);
 if s>0 and s%7=0 then insert into public.points_events(user_id,source,ref_id,points,event_date) values(uid,'streak_bonus',cid,50,d) on conflict do nothing; awarded:=60; end if;
 return jsonb_build_object('checkInId',cid,'pointsAwarded',awarded,'streak',s);
exception when unique_violation then raise exception using errcode='23505',message='Check-in de hoje já realizado'; end; $$;

create or replace function public.rpc_complete_task(task_id bigint) returns integer language plpgsql security definer set search_path=pg_catalog,public as $$ declare uid uuid:=auth.uid(); begin if uid is null then raise exception using errcode='28000'; end if; update public.daily_tasks set done=true,done_at=now() where id=task_id and user_id=uid and not done; if found then insert into public.points_events(user_id,source,ref_id,points) values(uid,'task_done',task_id,5) on conflict do nothing; return 5; end if; return 0; end; $$;
create or replace function public.rpc_complete_goal(goal_id bigint) returns integer language plpgsql security definer set search_path=pg_catalog,public as $$ declare uid uuid:=auth.uid(); begin if uid is null then raise exception using errcode='28000'; end if; update public.goals set progress=1,completed_at=coalesce(completed_at,now()) where id=goal_id and user_id=uid and completed_at is null; if found then insert into public.points_events(user_id,source,ref_id,points) values(uid,'goal_done',goal_id,30) on conflict do nothing; return 30; end if; return 0; end; $$;
create or replace function public.rpc_join_squad(code text) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$ declare uid uuid:=auth.uid(); sid bigint; affected integer; begin if uid is null or code is null or length(btrim(code))=0 then raise exception using errcode='22023',message='Convite inválido'; end if; select id into sid from public.squads where invite_code=upper(btrim(code)); if sid is null then raise exception using errcode='22023',message='Convite inválido'; end if; insert into public.squad_members(squad_id,user_id) values(sid,uid) on conflict do nothing; get diagnostics affected=row_count; if affected=0 then raise exception using errcode='23505',message='Você já participa deste grupo'; end if; return sid; end; $$;
create or replace function public.rpc_create_squad(squad_name text,squad_subtitle text default '',season_end timestamptz default null) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$ declare uid uuid:=auth.uid(); sid bigint; begin if uid is null then raise exception using errcode='28000',message='Sessão inválida'; end if; if squad_name is null or char_length(btrim(squad_name)) not between 1 and 100 then raise exception using errcode='22023',message='Nome de squad inválido'; end if; insert into public.squads(name,subtitle,season_ends_at,created_by) values(btrim(squad_name),left(coalesce(squad_subtitle,''),160),season_end,uid) returning id into sid; insert into public.squad_members(squad_id,user_id) values(sid,uid); return sid; end; $$;

create or replace function public.fn_heatmap(uid uuid default auth.uid(),weeks integer default 4) returns table(check_date date,intensity integer) language sql stable security invoker set search_path=pg_catalog,public as $$ select d::date,least(4,greatest(0,coalesce(c.minutes/30,0)+(select count(*)::int from public.daily_tasks t where t.user_id=uid and t.task_date=d::date and t.done)))::int from generate_series((timezone('America/Sao_Paulo',now()))::date-greatest(1,least(52,coalesce(weeks,4)))*7+1,(timezone('America/Sao_Paulo',now()))::date,interval '1 day') d left join public.check_ins c on c.user_id=uid and c.check_date=d::date order by d; $$;
create or replace function public.fn_squad_ranking(target_squad bigint) returns table(user_id uuid,name text,weekly_points bigint,streak integer,rank bigint) language sql stable security definer set search_path=pg_catalog,public as $$ with scores as(select sm.user_id,p.name,coalesce(v.weekly,0)::bigint weekly_points,public.fn_streak(sm.user_id) streak from public.squad_members sm join public.profiles p on p.id=sm.user_id left join public.v_user_points v on v.user_id=sm.user_id where sm.squad_id=target_squad) select s.user_id,s.name,s.weekly_points,s.streak,rank() over(order by s.weekly_points desc,s.streak desc,s.name)::bigint from scores s where public.is_squad_member(target_squad); $$;

revoke all on function public.rpc_check_in(integer),public.rpc_complete_task(bigint),public.rpc_complete_goal(bigint),public.rpc_join_squad(text),public.rpc_create_squad(text,text,timestamptz),public.fn_streak(uuid),public.fn_heatmap(uuid,integer),public.fn_squad_ranking(bigint) from public,anon;
grant execute on function public.rpc_check_in(integer),public.rpc_complete_task(bigint),public.rpc_complete_goal(bigint),public.rpc_join_squad(text),public.rpc_create_squad(text,text,timestamptz),public.fn_streak(uuid),public.fn_heatmap(uuid,integer),public.fn_squad_ranking(bigint) to authenticated;
