import type { AuthChangeEvent, Session, User } from '@supabase/supabase-js'
import { supabase, supabaseConfigured } from '../lib/supabase'
import { fail, mapAuthError, ok, toAppError, type Result } from '../lib/result'
import type { Profile, SignUpMetadata } from '../types/domain'
export type AuthStateChangeCallback = (event: AuthChangeEvent, session: Session | null) => void
const notConfigured = <T>(): Result<T> => fail({ code: 'unknown', message: 'Supabase não está configurado. Defina EXPO_PUBLIC_SUPABASE_URL e EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY (ou ANON_KEY) e reinicie o app.' })
const validation = (message: string): Result<never> => fail({ code: 'validation', message })
export async function getSession(): Promise<Result<Session | null>> { if (!supabase || !supabaseConfigured) return notConfigured(); try { const { data, error } = await supabase.auth.getSession(); return error ? fail(mapAuthError(error)) : ok(data.session) } catch (error) { return fail(toAppError(error, 'Não foi possível recuperar sua sessão.')) } }
export async function signIn(email: string, password: string): Promise<Result<{ session: Session; user: User }>> { if (!email.trim() || !password) return validation('Informe seu e-mail e sua senha.'); if (!supabase || !supabaseConfigured) return notConfigured(); try { const { data, error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (error) return fail(mapAuthError(error)); if (!data.session || !data.user) return fail({ code: 'auth', message: 'Login sem sessão. Tente novamente.' }); return ok({ session: data.session, user: data.user }) } catch (error) { return fail(toAppError(error, 'Não foi possível entrar.')) } }
export async function signUp(name: string, email: string, password: string, metadata?: SignUpMetadata): Promise<Result<{ session: Session | null; user: User | null }>> { if (!name.trim()) return validation('Informe seu nome.'); if (!email.trim()) return validation('Informe seu e-mail.'); if (password.length < 6) return validation('A senha deve ter pelo menos 6 caracteres.'); if (!supabase || !supabaseConfigured) return notConfigured(); try { const { data, error } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { name: name.trim(), ...metadata } } }); if (error) return fail(mapAuthError(error)); return ok({ session: data.session, user: data.user }) } catch (error) { return fail(toAppError(error, 'Não foi possível criar sua conta.')) } }
export async function signOut(): Promise<Result<null>> { if (!supabase || !supabaseConfigured) return notConfigured(); try { const { error } = await supabase.auth.signOut(); return error ? fail(mapAuthError(error)) : ok(null) } catch (error) { return fail(toAppError(error, 'Não foi possível sair.')) } }
export function onAuthChange(callback: AuthStateChangeCallback): () => void { if (!supabase || !supabaseConfigured) return () => undefined; const { data: { subscription } } = supabase.auth.onAuthStateChange(callback); return () => subscription.unsubscribe() }
export async function getProfile(userId: string): Promise<Result<Profile | null>> { if (!userId) return validation('Usuário inválido.'); if (!supabase || !supabaseConfigured) return notConfigured(); try { const { data, error } = await supabase.from('profiles').select('id,name,badge,created_at').eq('id', userId).maybeSingle(); if (error) return fail(toAppError(error, 'Não foi possível carregar seu perfil.')); return ok(data as Profile | null) } catch (error) { return fail(toAppError(error, 'Não foi possível carregar seu perfil.')) } }
